---

title: "Dimensionnement d'une alimentation Flyback"
date: 2009-06-02
comments: true
categories:
 - Hacheurs
 - Flyback
 - hacheur
 - Électronique de Puissance
---

<div class='post'>
Un des projets de 4ème année consistait à réaliser une alimentation à découpage de type Flyback (120 V en entrée - 48 V sous 2 A en sortie en nominale).Nous avons pour l'occasion revu la théorie nécessaire et réaliser le projet sans qu'il n'explose ! Nous vous proposons notre étude et notre démarche ainsi qu'une feuille Calc qui vous permettra de refaire automatiquement les calculs pour des conditions d'applications différentes. Les informations sont accessibles sur la page électronique.<br /><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://4.bp.blogspot.com/-CKgf2D5GX9Q/TfCaY5wRuKI/AAAAAAAAMq0/zFRLI3TPEj0/s1600/P1120698.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="240" src="http://4.bp.blogspot.com/-CKgf2D5GX9Q/TfCaY5wRuKI/AAAAAAAAMq0/zFRLI3TPEj0/s320/P1120698.JPG" width="320" /></a></div><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://4.bp.blogspot.com/-oD4vZli4Kdc/TfCaYhinI2I/AAAAAAAAMqw/Q59o-FFCISI/s1600/P1120697.JPG" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="240" src="http://4.bp.blogspot.com/-oD4vZli4Kdc/TfCaYhinI2I/AAAAAAAAMqw/Q59o-FFCISI/s320/P1120697.JPG" width="320" /></a></div><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://1.bp.blogspot.com/-_65VQhelrHQ/TfCaW50udkI/AAAAAAAAMqs/yFHew5yHdHQ/s1600/isis.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="122" src="http://1.bp.blogspot.com/-_65VQhelrHQ/TfCaW50udkI/AAAAAAAAMqs/yFHew5yHdHQ/s320/isis.png" width="320" /></a></div><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://2.bp.blogspot.com/-EtZnC9zGdM8/TfCaYvcm6OI/AAAAAAAAMq4/FtLkCXO8WaQ/s1600/top.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="167" src="http://2.bp.blogspot.com/-EtZnC9zGdM8/TfCaYvcm6OI/AAAAAAAAMq4/FtLkCXO8WaQ/s320/top.jpg" width="320" /></a></div><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://4.bp.blogspot.com/-5sG1W69qfuw/TfCaWr5NE2I/AAAAAAAAMqk/xKXI4AmXD8g/s1600/bottom.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="167" src="http://4.bp.blogspot.com/-5sG1W69qfuw/TfCaWr5NE2I/AAAAAAAAMqk/xKXI4AmXD8g/s320/bottom.jpg" width="320" /></a></div><br /><div class="separator" style="clear: both; text-align: center;"><a href="http://3.bp.blogspot.com/-NRbNYZI3onE/TfCaWiRm3QI/AAAAAAAAMqg/EHYM5mnp_qc/s1600/yg.jpg" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" src="http://3.bp.blogspot.com/-NRbNYZI3onE/TfCaWiRm3QI/AAAAAAAAMqg/EHYM5mnp_qc/s1600/yg.jpg" /></a></div><br /><br /><br /><br /><div style="text-align: left;"><b><br /></b></div><br /><div style="text-align: left;"><b><br /></b><br /></div><div style="text-align: left;"></div></div>
