---

title: "Réengagement abusif chez SFR - suite et fin"
date: 2012-07-11
comments: true
---

<div class='post'>
<div dir="ltr" style="text-align: left;" trbidi="on">Je réponds à mon billet précédent concernant des pratiques un peu douteuses de la part de SFR. Je vous donne ici la fin de l'histoire.<br />Après l'envoi d'une lettre avec accusé de réception au service-consommateurs de l'opérateur, un email à la DGGCRF, un courrier à la DDPP du Bas-Rhin, celle du Calvados (ne jamais faire les choses à moitié) et un <a href="http://forum.lesarnaques.com/telephonie-mobile-internet-cles3g/sfr-reengagement-abusif-ineligibilite-loi-chatel-t136746.html" target="_blank">post</a> sur le forum &nbsp;du site<a href="http://forum.lesarnaques.com/" target="_blank"> lesarnaques.com</a>, je reçois un appel 4 jours plus tard de la part du service-consommateurs. La personne au bout du fil me confirme qu'aucun papier n' a été signé et annule de suite l'offre promotionnelle. Ceci me permet de bénéficier immédiatement, si je le souhaite, de la loi Chatel et je n'ai rien à rembourser.<br />Un retournement de situation aussi rapide montre que SFR savait depuis le départ que ce réengagement était abusif. Une fois la réclamation faite, ils n'avaient d'autre choix que de l'annuler.<br />Je pense que ces méthodes traduisent une difficulté de la part de SFR pour garder des clients et plutôt que de leur offrir des prestations aux meilleurs prix, il utilises ses CGV pour piéger le client et s'assurer de toucher le maximum. Je trouve ça dommage de la part d'une grande enseigne qui dénonce les méthodes du nouvel arrivant ...<br />Quoi qu'il en soit, dans n'importe quel litige de cette sorte, n'oubliez pas de faire un tour sur internet pour voir si votre problème n'a pas été soulevé et signaler votre cas à la DGCCRF via internet et à la DDPP de votre département. Cela permettra&nbsp;&nbsp;à ces institutions&nbsp;en cas de grand nombre de litiges similaires d'intervenir et d'empêcher à d'autres personnes de connaître le même problème.<br />Pour ma part, il ne manque plus que de savoir si mon N1 est désimlocké ...</div></div>
